title: "Farhan Ashraf"
email: mriceflame@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is portfolio website of Mriceflame Farhan Ashraf
hosted on Github Pages.
# Root directory for your portfolio. On GitHub Pages, this is the name of your repository.
baseurl: "/mriceflame.github.io"
# Protocol + hostname for your portfolio. On GitHub Pages, this is https://yourusername.github.io
url: "https://mriceflame.github.io" 
twitter_username: mriceflame
github_username: mriceflame
form_url: "https://formspree.io/f/xgerwayv"
social_image: "./assets/img/social-link.jpg"
social_image_alt: "Search mriceflame on google"
google_analytics_measurement_id: UA-86532413-1

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
